comData.MvcClient/Controllers/ClienteController.cs
using comData.DesktopClient.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace comData.MvcClient.Controllers
{
    public class ClienteController : Controller
    {
        HttpClient client;
        string url = "http://localhost:12573/api/cliente";
    
        public ClienteController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json")); 
        }

        public ActionResult Index()
        {
            return View("mantenimiento-cliente");
        }


        [HttpPost]
        public async Task<JsonResult> getTodosClientesR()
        {

            return Json(await getTodosClientes());
        }

        [HttpPost]
        public async Task<JsonResult> getClienteIdR(ClienteResource cliente)
        {

            return Json(await getClienteId(cliente));
        }
        [HttpPost]
        public async Task<JsonResult> createClienteR(ClienteResource cliente)
        {

            return Json(await createCliente(cliente));
        }
        [HttpPost]
        public async Task<JsonResult> updateClienteR(ClienteResource cliente)
        {

            return Json(await updateCliente(cliente));
        }
        [HttpPost]
        public async Task<JsonResult> deleteClienteR(ClienteResource cliente)
        {
            bool elimino;
            elimino = await deleteCliente(cliente);
            if (elimino)
            {
                return Json(new { result = elimino });
            }           
            return Json(new { result = elimino });
        }
         async Task<IEnumerable<ClienteResource>> getTodosClientes()
        {

            HttpResponseMessage response = await client.GetAsync(url);
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<ClienteResource> clienteResources = await response.Content.ReadAsAsync<IEnumerable<ClienteResource>>();
                return clienteResources;
            }
            return null;

        }
         async Task<ClienteResource> createCliente(ClienteResource cliente)
         {            
             HttpResponseMessage response = await client.PostAsJsonAsync(url, cliente);
             if (response.IsSuccessStatusCode)
             {
                 ClienteResource newCliente = await response.Content.ReadAsAsync<ClienteResource>();
                 return newCliente;

             }
             return cliente;

         }

         async Task<ClienteResource> getClienteId(ClienteResource cliente)
         {

             HttpResponseMessage response = await client.GetAsync(url + "/" + cliente.Id);
             if (response.IsSuccessStatusCode)
             {
                 ClienteResource clienteResource = await response.Content.ReadAsAsync<ClienteResource>();
                 return clienteResource;
             }
             return null;

         }

         async Task<ClienteResource> updateCliente(ClienteResource cliente)
         {

             HttpResponseMessage response = await client.PutAsJsonAsync(url + "/" + cliente.Id, cliente);
             if (response.IsSuccessStatusCode)
             {
                 ClienteResource updatedCliente = await response.Content.ReadAsAsync<ClienteResource>();
                 return updatedCliente;
             }
             return cliente;

         }
         async Task<bool> deleteCliente(ClienteResource cliente)
         {

             HttpResponseMessage response = await client.DeleteAsync(url + "/" + cliente.Id);
             if (response.IsSuccessStatusCode)
             {
                 return true;
             }
             return false;
         }

    }
}

comData.MvcClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace comData.MvcClient.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

comData.MvcClient/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace comData.MvcClient.Controllers
{
    public class NavController : Controller
    {
        //
        // GET: /Nav/

        public PartialViewResult Menu()
        {
            return PartialView();
        }

    }
}

comData.MvcClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<p>Bienvenido</p>

comData.MvcClient/Views/Nav/Menu.cshtml
<style type="text/css">
    .tree, .tree ul {
        margin: 0;
        padding: 0;
        list-style: none;
    }

        .tree ul {
            margin-left: 1em;
            position: relative;
        }

            .tree ul ul {
                margin-left: .5em;
            }

            .tree ul:before {
                content: "";
                display: block;
                width: 0;
                position: absolute;
                top: 0;
                bottom: 0;
                left: 0;
                border-left: 1px solid;
            }

        .tree li {
            margin: 0;
            padding: 0 1em;
            line-height: 2em;
            color: #369;
            font-weight: 700;
            position: relative;
        }

        .tree ul li:before {
            content: "";
            display: block;
            width: 10px;
            height: 0;
            border-top: 1px solid;
            margin-top: -1px;
            position: absolute;
            top: 1em;
            left: 0;
        }

        .tree ul li:last-child:before {
            background: #fff;
            height: auto;
            top: 1em;
            bottom: 0;
        }

    .indicator {
        margin-right: 5px;
    }

    .tree li a {
        text-decoration: none;
        color: #369;
    }

    .tree li button, .tree li button:active, .tree li button:focus {
        text-decoration: none;
        color: #369;
        border: none;
        background: transparent;
        margin: 0px 0px 0px 0px;
        padding: 0px 0px 0px 0px;
        outline: 0;
    }
</style>
<script type="text/javascript">
    jQuery(function ($) {
        $('#tree1').treed();
        $('#tree2').treed({ openedClass: 'glyphicon-folder-open', closedClass: 'glyphicon-folder-close' });
        $('#tree3').treed({ openedClass: 'glyphicon-chevron-right', closedClass: 'glyphicon-chevron-down' });
    });

    function MostrarPAdmin() {
        var tree1 = $('#tree1');

        var li_00 = $('<li/>');

        var a_10 = $('<a/>');
        var ul_10 = $('<ul/>');

        var a_21 = '@Html.ActionLink("Principal", "Index", "Home")';

        var li_21 = $('<li/>');
        var li_22 = $('<li/>');

        var ul_30 = $('<ul/>');

        var li_46 = $('<li/>');


        var a_56 = '@Html.ActionLink("Mantenimiento Cliente", "Index", "Cliente")';


        a_10.text('comData').attr('href', '#');

        li_21.append(a_21);

        li_22.text('Aréa de Ventas');


        li_46.append(a_56);

        ul_30.append(li_46);

        li_22.append(ul_30);


        ul_10.append(li_21).append(li_22);

        li_00.append(a_10).append(ul_10);
        tree1.append(li_00);
    }

 

    $(document).ready(function () {
        MostrarPAdmin();

    });
</script>

<ul id="tree1"></ul>

comData.MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js" integrity="sha256-4iQZ6BVL4qNKlQ27TExEhBN1HFPvAvAMbFavKKosSWQ=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/css/jquery.dataTables_themeroller.css" integrity="sha256-/I46pnUiYUyilMyUMv08B9tEUgxxuWJJCqoyl6+Cz+I=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/js/jquery.dataTables.min.js" integrity="sha256-t5ZQTZsbQi8NxszC10CseKjJ5QeMw5NINtOXQrESGSU=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" integrity="sha256-yMjaV542P+q1RnH6XByCPDfUFhmOafWbeLPmqKh11zo=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js" integrity="sha256-5YmaxAwMjIpMrVlK84Y/+NjCpKnFYa8bWWBbUHSBGfU=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js" integrity="sha256-sfG8c9ILUB8EXQ5muswfjZsKICbRIJUG/kBogvvV5sY=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" integrity="sha256-WolrNTZ9lY0QL5f0/Qi1yw3RGnDLig2HVLYkrshm7Y0=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js" integrity="sha256-56zsTlMwzGRtLC4t51alLh5cKYvi0hnbhEXQTVU/zZQ=" crossorigin="anonymous"></script>

      <script src="~/Scripts/jstree.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/all.min.js" integrity="sha256-MAgcygDRahs+F/Nk5Vz387whB4kSK9NXlDN3w58LLq0=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />

    <title>@ViewBag.Title</title>
</head>
<body>
    <script type="text/javascript">
    $(document).ready(function () {

  
        var menu_user = $('#menu_user');
        menu_user.append('<span class="glyphicon glyphicon-user">' + 'Invitado' + '</span>')

    })
    </script>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">comData</a>
        <ul class="nav navbar-nav navbar-right">
            <li><a id="menu_user" href="#"> </a></li>
            <li><a id="menu_salir" href="#"><span class="glyphicon glyphicon-log-in"></span> Salir</a></li>
        </ul>
    </div>
    <div class="row panel">
        <div id="categories" class="col-md-2">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>